Update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -152,8 +152,13 @@ jobs:
       - name: Get existing release ID
         if: ${{ env.MISSING_ASSETS != '' && env.MISSING_ASSETS != 'null' }}
         run: |
-          release_id=$(jq -r '.id' <<< "$existing_release_info")
-          echo "RELEASE_ID=$release_id" | tee -a $GITHUB_ENV
+          release_id=$(echo "$existing_release_info" | jq -r '.id')
+          if [ -z "$release_id" ]; then
+            echo "Release ID not found. Aborting."
+            exit 1
+          else
+            echo "RELEASE_ID=$release_id" | tee -a $GITHUB_ENV
+          fi
 
       - name: Print MISSING_ASSETS
         if: ${{ env.MISSING_ASSETS != '' && env.MISSING_ASSETS != 'null' }}
